services:

  application:
    image: docker-php/php-demo:prod
    build:
      dockerfile: ./.include/php-demo/Dockerfile
      target: app_production
      context: .
    deploy:
      replicas: 3

  proxy:
    image: docker-php/nginx-php:prod
    build:
      dockerfile: ./.include/php-demo/Dockerfile
      target: proxy
      context: .
    ports:
      - 80:80
    deploy:
      replicas: 2
