services:

  application:
    image: docker-php/php-demo:local
    build:
      dockerfile: ./.docker/Dockerfile
      target: app_development
      context: .
    volumes:
      - ./srcs:/var/www/html:ro

  proxy:
    image: docker-php/nginx-php:local
    build:
      dockerfile: ./.docker/Dockerfile
      target: proxy
      context: .
    volumes:
      - ./srcs:/var/www/html:ro
    ports:
      - 80:80
